version: '3'

services:
  f5-tts:
    build: .
    platform: linux/arm64
    ports:
      - "8000:8000"
    volumes:
      - ./data:/workspace/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 